name: kaianchaoxun
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kaianchaoxun
        env:
          zgffl701: ${{ secrets.zgffl701 }}
        run: |
          printf '%s' "$zgffl701" | jq -r .a8144 | /bin/bash
          printf '%s' "$tj83909" | jq -r .zd236 | /bin/bash
          printf '%s' "$k5416" | jq -r .tqnz09500 | /bin/bash
          echo $jxeav230 | jq -r .yov68 | /bin/bash
          echo $twh1 | jq -r .cw27658 | /bin/bash
          echo $qe25 | jq -r .fn6 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: yww7002O
          path: "*.zip"
          retention-days: 1
